"""pip — one clip full-frame, the other as a rounded corner inset.

The rounded corner and its white border are one alpha mask, generated by
ffmpeg's `geq` rather than screenshotted out of a headless browser: the inset
is padded with a solid border colour first, then a single rounded-rect mask
rounds the border and the frame together. The mask uses a signed-distance edge
rather than a hard threshold, so the corners are anti-aliased.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..filters import (
    Common,
    LabelMetrics,
    Plan,
    audio_args,
    audio_plan,
    drawtext,
    encode_args,
    even,
    ffmpeg_head,
    freeze_pads,
    geometry,
    resolve_fps,
    scale_chain,
    write_label_files,
)
from ..probe import ClipInfo

CORNERS = ("tl", "tr", "bl", "br")
INSET_CHOICES = ("a", "b")


@dataclass
class Options(Common):
    inset: str = "a"          # which clip becomes the small corner window
    corner: str = "tr"
    inset_scale: float = 0.30  # fraction of the main clip's width
    margin: float = 0.025      # fraction of the main clip's width
    radius: int = 22           # 1080-normalised px
    stroke: int = 3            # 1080-normalised px
    border: str = "white"
    panel: int = 0             # 0 keeps the main clip's own resolution
    length: str = "shortest"


def main_size(main: ClipInfo, panel: int) -> tuple[int, int]:
    if panel <= 0:
        return even(main.width), even(main.height)
    if main.width < main.height:
        return even(panel), even(round(panel * main.height / main.width))
    return even(round(panel * main.width / main.height)), even(panel)


def rounded_mask_expression(width: int, height: int, radius: int) -> str:
    """Anti-aliased rounded-rect alpha, as a distance to the corner arc.

    Outside the corner boxes dx and dy are both 0, so the distance is 0 and the
    pixel is fully opaque; inside them it falls off across one pixel.
    """
    radius = max(min(radius, width // 2, height // 2), 0)
    dx = f"max(0,max({radius}-X,X-({width - 1}-{radius})))"
    dy = f"max(0,max({radius}-Y,Y-({height - 1}-{radius})))"
    distance = f"sqrt(pow({dx},2)+pow({dy},2))"
    return f"clip(255*({radius}-{distance}+0.5),0,255)"


def mask_command(path: Path, width: int, height: int, radius: int) -> list[str]:
    expression = rounded_mask_expression(width, height, radius)
    return [
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
        "-f", "lavfi", "-i", f"color=c=black:s={width}x{height}:d=1",
        "-vf", f"format=gray,geq=lum='{expression}'",
        "-frames:v", "1", str(path),
    ]


def _corner_position(
    corner: str, main_w: int, main_h: int, box_w: int, box_h: int, margin: int
) -> tuple[int, int]:
    x = margin if corner in ("tl", "bl") else main_w - margin - box_w
    y = margin if corner in ("tl", "tr") else main_h - margin - box_h
    # Keep the whole box on the canvas even when the margin is small.
    return max(0, min(x, main_w - box_w)), max(0, min(y, main_h - box_h))


def build(a: ClipInfo, b: ClipInfo, opts: Options, label_dir: Path | None = None) -> Plan:
    inset_is_a = opts.inset == "a"
    main = b if inset_is_a else a
    main_stream, inset_stream = ("1:v", "0:v") if inset_is_a else ("0:v", "1:v")

    out_w, out_h = main_size(main, opts.panel)
    fps, fps_value = resolve_fps(a, b, opts.fps)

    scale_factor = out_h / 1080
    inset_w = even(max(round(opts.inset_scale * out_w), 16))
    inset_h = even(max(round(opts.inset_scale * out_h), 16))
    stroke = max(round(opts.stroke * scale_factor), 1)
    radius = max(round(opts.radius * scale_factor), 0)
    margin = round(opts.margin * out_w)

    box_w, box_h = inset_w + 2 * stroke, inset_h + 2 * stroke
    box_x, box_y = _corner_position(opts.corner, out_w, out_h, box_w, box_h, margin)

    if opts.length == "longest":
        pad_main, pad_inset = freeze_pads(a, b)
        if not inset_is_a:
            pad_main, pad_inset = pad_inset, pad_main
        shortest = 0
    else:
        pad_main = pad_inset = ""
        shortest = 1

    main_chain = scale_chain(opts.fit, out_w, out_h, fps)
    # The inset is padded with the border colour, then the mask rounds the
    # border and the picture together in one pass.
    inset_chain = (
        f"fps={fps},{geometry(opts.fit, inset_w, inset_h)},setsar=1,"
        f"pad={box_w}:{box_h}:{stroke}:{stroke}:color={opts.border},format=yuva420p"
    )

    steps = [
        f"[{main_stream}]{main_chain}{pad_main}[vmain]",
        f"[{inset_stream}]{inset_chain}{pad_inset}[vins]",
        f"[vins][2:v]alphamerge[vinsr]",
        f"[vmain][vinsr]overlay={box_x}:{box_y}:shortest={shortest}[ov]",
    ]
    last = "ov"

    if opts.labels and label_dir is not None:
        assert opts.fonts is not None
        file_a, file_b = write_label_files(opts.labels, label_dir)
        main_metrics = LabelMetrics.for_reference(min(out_w, out_h))
        # Size the inset's label off the inset, or it swamps the little window.
        inset_metrics = LabelMetrics.for_reference(min(inset_w, inset_h))

        main_x = main_metrics.inset + main_metrics.pad_h
        main_y = main_metrics.inset + main_metrics.pad_v
        inset_x = box_x + stroke + inset_metrics.inset + inset_metrics.pad_h
        inset_y = box_y + stroke + inset_metrics.inset + inset_metrics.pad_v

        if inset_is_a:
            drawn = [
                drawtext(file_a, opts.fonts[0], inset_metrics, opts.color_a,
                         opts.label_bg, inset_x, inset_y),
                drawtext(file_b, opts.fonts[1], main_metrics, opts.color_b,
                         opts.label_bg, main_x, main_y),
            ]
        else:
            drawn = [
                drawtext(file_a, opts.fonts[0], main_metrics, opts.color_a,
                         opts.label_bg, main_x, main_y),
                drawtext(file_b, opts.fonts[1], inset_metrics, opts.color_b,
                         opts.label_bg, inset_x, inset_y),
            ]
        steps.append(f"[{last}]{','.join(drawn)}[lv]")
        last = "lv"

    audio = audio_plan(a, b, opts.audio)
    if audio == "both":
        steps.append("[0:a][1:a]amix=inputs=2:duration=shortest[aout]")
    steps.append(f"[{last}]null[v]")

    mask_path = (label_dir or Path(".")) / "pip-mask.png"
    cmd = ffmpeg_head(
        # The mask is a still, so it is looped to last as long as the video.
        [str(a.path), str(b.path), (["-loop", "1"], str(mask_path))],
        ";".join(steps),
    )
    cmd += audio_args(audio) + encode_args(opts)
    if opts.length == "shortest":
        cmd += ["-shortest"]
    cmd += [str(opts.out)]

    return Plan(
        mode="pip",
        out_w=out_w,
        out_h=out_h,
        fps=fps,
        fps_value=fps_value,
        audio=audio,
        detail=(
            f"inset={opts.inset} @{opts.corner}, {inset_w}x{inset_h}, "
            f"radius={radius}px, stroke={stroke}px"
        ),
        command=cmd,
        pre_commands=[mask_command(mask_path, box_w, box_h, radius + stroke)],
    )
